# arrays

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr.shape

(10,)

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.ndim

1

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.float32)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [8]:
arr.dtype

dtype('float32')

In [9]:
len(arr)

10

In [10]:
arr.size

10

In [11]:
arr = arr.astype(np.int64)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr = np.arange(0,40,1.5)
arr

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5, 24. , 25.5, 27. , 28.5, 30. , 31.5,
       33. , 34.5, 36. , 37.5, 39. ])

In [14]:
arr = np.linspace(0,30,100)
arr

array([ 0.        ,  0.3030303 ,  0.60606061,  0.90909091,  1.21212121,
        1.51515152,  1.81818182,  2.12121212,  2.42424242,  2.72727273,
        3.03030303,  3.33333333,  3.63636364,  3.93939394,  4.24242424,
        4.54545455,  4.84848485,  5.15151515,  5.45454545,  5.75757576,
        6.06060606,  6.36363636,  6.66666667,  6.96969697,  7.27272727,
        7.57575758,  7.87878788,  8.18181818,  8.48484848,  8.78787879,
        9.09090909,  9.39393939,  9.6969697 , 10.        , 10.3030303 ,
       10.60606061, 10.90909091, 11.21212121, 11.51515152, 11.81818182,
       12.12121212, 12.42424242, 12.72727273, 13.03030303, 13.33333333,
       13.63636364, 13.93939394, 14.24242424, 14.54545455, 14.84848485,
       15.15151515, 15.45454545, 15.75757576, 16.06060606, 16.36363636,
       16.66666667, 16.96969697, 17.27272727, 17.57575758, 17.87878788,
       18.18181818, 18.48484848, 18.78787879, 19.09090909, 19.39393939,
       19.6969697 , 20.        , 20.3030303 , 20.60606061, 20.90

In [15]:
arr = np.random.random((5,))
arr.size

5

In [16]:
arr

array([0.65815511, 0.35644159, 0.58680521, 0.58775491, 0.25620839])

In [17]:
arr = np.random.random_sample((5,))
arr.size

5

In [18]:
arr

array([0.54058525, 0.7181024 , 0.79267196, 0.47302511, 0.0569927 ])

In [43]:
np.random.randint(-10,10,20)

array([-10,  -6,  -8,  -6,  -8,   2,   1, -10,   3,   7,   8,   3,   1,
        -8,  -5,  -3,   4,  -4,   4, -10])

In [44]:
np.random.randint(-5,5,10)

array([ 3, -5,  0, -4, -5,  4,  1,  1, -2,  2])

# range of random numbers from a to b: (b - a) * np.random + a | b > a

In [19]:
arr = (10 - -5) * np.random.random((20,)) + -5
arr

array([-4.83854428, -4.17102192, -4.39743605,  6.88159754, -0.9434441 ,
        3.41227428,  9.46914525,  1.08217409,  2.93374278,  6.73950774,
        9.19930366,  6.84218178, -4.19549421, -0.18318674,  5.86616608,
        0.40074524, -0.03560917,  7.32882755,  1.58508354,  8.56761318])

In [23]:
arr = (20 - 15) * np.random.random_sample((20,)) + 15
arr

array([19.82706918, 19.30324306, 18.06827371, 18.1303213 , 17.45134794,
       15.64123205, 17.59422522, 19.92434911, 17.99563085, 15.43469416,
       17.98706117, 17.86168706, 18.75465174, 18.82045939, 17.72835802,
       18.26584254, 19.54451597, 18.91436471, 16.26987025, 16.93642498])

# operations

In [24]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [25]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [26]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [27]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [28]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [29]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [30]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [33]:
arr_1 = arr
arr_2 = np.array([5,6,7,8,9])
arr_1, arr_2

(array([1, 2, 3, 4, 5]), array([5, 6, 7, 8, 9]))

In [34]:
arr_3 = arr_1 + arr_2
arr_3

array([ 6,  8, 10, 12, 14])

**[ 1+5, 6+2, 7+3, 8+4, 9+5 \] = [ 6, 8, 10, 12, 14 \]**

In [37]:
arr_1 * arr_2

array([ 5, 12, 21, 32, 45])

In [39]:
arr_1 - arr_2

array([-4, -4, -4, -4, -4])

In [40]:
arr_1 / arr_2

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [41]:
arr_1 * 2

array([ 2,  4,  6,  8, 10])

In [42]:
arr_1 ** 2

array([ 1,  4,  9, 16, 25])

# functions

In [45]:
arr = np.random.randint(10,100,10)
arr

array([99, 65, 75, 91, 13, 80, 13, 59, 57, 10])

In [46]:
arr.max()

np.int64(99)

In [47]:
arr.min()

np.int64(10)

In [48]:
arr.mean()

np.float64(56.2)

In [49]:
arr.sum()

np.int64(562)

In [50]:
arr.std()

np.float64(31.489045714343266)

In [51]:
np.median(arr)

np.float64(62.0)

In [53]:
arr < 70

array([False,  True, False, False,  True, False,  True,  True,  True,
        True])

# working with arrays

In [55]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr = np.insert(arr,2,100)
arr

array([  0,   1, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [59]:
arr.sort()
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [60]:
arr2 = np.arange(10,20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
res = np.concatenate((arr,arr2))
res

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100,  10,
        11,  12,  13,  14,  15,  16,  17,  18,  19])

In [62]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [63]:
res = np.array_split(arr, 5)
res

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([ 10, 100])]

# indexes and multidimensional arrays

In [66]:
arr = np.arange(-10,1)
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [67]:
arr[0] = 100
arr

array([100,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [68]:
arr[5]

np.int64(-5)

In [69]:
arr[:5]

array([100,  -9,  -8,  -7,  -6])

In [70]:
arr[5:]

array([-5, -4, -3, -2, -1,  0])

In [71]:
arr[::-1]

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, 100])

In [73]:
arr[arr < -3]

array([-9, -8, -7, -6, -5, -4])

In [74]:
arr[(arr < -3) & (arr > -7)]

array([-6, -5, -4])

In [75]:
arr[(arr < -5) | (arr > -2)]

array([100,  -9,  -8,  -7,  -6,  -1,   0])

In [76]:
arr[:5] = 0
arr

array([ 0,  0,  0,  0,  0, -5, -4, -3, -2, -1,  0])

In [77]:
arr.sort()
arr

array([-5, -4, -3, -2, -1,  0,  0,  0,  0,  0,  0])

# matrices and multidimensional arrays

In [81]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)], dtype = np.float32)
matrix

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [82]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [83]:
matrix.shape

(3, 3)

In [84]:
matrix.size

9

In [85]:
matrix.ndim

2

In [89]:
m = matrix
m.reshape(1,9)

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float32)

In [91]:
m.reshape(3,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [93]:
m2 = matrix1
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [94]:
m2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [96]:
m = np.random.random((2,2))
m

array([[0.96799235, 0.40602753],
       [0.47428689, 0.16187379]])

In [102]:
m = np.random.random((10,10))
m

array([[0.21430687, 0.33650371, 0.69147421, 0.19277204, 0.90854098,
        0.30413623, 0.69048765, 0.34592862, 0.38199898, 0.68094395],
       [0.43543248, 0.12411181, 0.99843158, 0.85152787, 0.98378341,
        0.77649475, 0.29448662, 0.2831227 , 0.88722439, 0.48650378],
       [0.666634  , 0.00239401, 0.69822357, 0.47711078, 0.7245905 ,
        0.04634208, 0.90811363, 0.47232662, 0.99090068, 0.76578122],
       [0.41776454, 0.21340215, 0.05764779, 0.01610931, 0.24553226,
        0.56004062, 0.41606876, 0.84990703, 0.48749842, 0.04693576],
       [0.11621917, 0.20824143, 0.31387991, 0.3707091 , 0.3962512 ,
        0.21528831, 0.11414533, 0.14366491, 0.73357712, 0.33358672],
       [0.08224171, 0.32528569, 0.82753621, 0.46818796, 0.83243819,
        0.67618089, 0.41172675, 0.57644041, 0.62328836, 0.87961779],
       [0.94006788, 0.35634869, 0.56696475, 0.33057473, 0.97331075,
        0.32338527, 0.50347583, 0.05262099, 0.94162969, 0.22016809],
       [0.26726905, 0.16888758, 0.0983780

In [103]:
m = np.resize(m,(2,2))
m

array([[0.21430687, 0.33650371],
       [0.69147421, 0.19277204]])

In [105]:
m = np.arange(10,20).reshape(5,2)
m

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

# special matrices

In [107]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [108]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [109]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [110]:
np.full((4,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [111]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# matrix operations

In [112]:
m1 = np.array([[1,2,],[3,4]])
m2 = np.array([[5,6],[7,8]])
m1, m2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [113]:
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [114]:
m1 - m2

array([[-4, -4],
       [-4, -4]])

In [115]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [116]:
m1 / m2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [117]:
m1 ** m2

array([[    1,    64],
       [ 2187, 65536]])

In [120]:
m1 // m2

array([[0, 0],
       [0, 0]])

In [121]:
m1.dot(m2)

array([[19, 22],
       [43, 50]])

In [122]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
m = np.delete(m,1,axis=0)

In [128]:
m = np.delete(m,1,axis=1)

In [129]:
np.sin(m)

array([[0.84147098, 0.14112001],
       [0.6569866 , 0.41211849]])

In [130]:
np.log(m)

array([[0.        , 1.09861229],
       [1.94591015, 2.19722458]])

In [131]:
np.sum(m)

np.int64(20)

In [132]:
np.max(m)

np.int64(9)

In [133]:
m.max()

np.int64(9)

In [135]:
m

array([[1, 3],
       [7, 9]])

In [138]:
m.max(axis=0) # vertically

array([7, 9])

In [139]:
m.max(axis=1) # horizontally

array([3, 9])

In [140]:
np.mean(m,axis=0)

array([4., 6.])

In [141]:
np.mean(m,axis=1)

array([2., 8.])

In [142]:
m ** 2

array([[ 1,  9],
       [49, 81]])

In [143]:
m

array([[1, 3],
       [7, 9]])

In [152]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1 = np.array([[10,11,12],[13,14,15],[16,17,18]])
m, m1

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [153]:
np.concatenate((m,m1),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [154]:
np.concatenate((m,m1),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [155]:
np.hstack((m,m1))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [156]:
np.vstack((m,m1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [157]:
np.split(m,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [158]:
np.split(m,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [160]:
np.append(m,np.array([1,2,3]))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])

In [161]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# indexing

In [162]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
m[1,2]

np.int64(6)

In [164]:
m[1]

array([4, 5, 6])

In [165]:
m[:,2]

array([3, 6, 9])

In [167]:
m[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [169]:
m[m > 2]

array([3, 4, 5, 6, 7, 8, 9])

# special operations

In [170]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [173]:
m.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
np.trace(m)

np.int64(15)

In [177]:
np.linalg.det(m)

np.float64(0.0)

In [178]:
np.linalg.matrix_rank(m)

np.int64(2)